# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import servicio_pb2 as servicio__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servicio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SistemaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listo = channel.unary_unary(
                '/Sistema/Listo',
                request_serializer=servicio__pb2.Nulo.SerializeToString,
                response_deserializer=servicio__pb2.Nulo.FromString,
                _registered_method=True)
        self.SolicitudOperacion = channel.unary_unary(
                '/Sistema/SolicitudOperacion',
                request_serializer=servicio__pb2.OperacionRequest.SerializeToString,
                response_deserializer=servicio__pb2.ResultadoReceive.FromString,
                _registered_method=True)
        self.OperacionParcial = channel.unary_unary(
                '/Sistema/OperacionParcial',
                request_serializer=servicio__pb2.OperacionRequest.SerializeToString,
                response_deserializer=servicio__pb2.ResultadoReceive.FromString,
                _registered_method=True)


class SistemaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Listo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolicitudOperacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OperacionParcial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SistemaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listo': grpc.unary_unary_rpc_method_handler(
                    servicer.Listo,
                    request_deserializer=servicio__pb2.Nulo.FromString,
                    response_serializer=servicio__pb2.Nulo.SerializeToString,
            ),
            'SolicitudOperacion': grpc.unary_unary_rpc_method_handler(
                    servicer.SolicitudOperacion,
                    request_deserializer=servicio__pb2.OperacionRequest.FromString,
                    response_serializer=servicio__pb2.ResultadoReceive.SerializeToString,
            ),
            'OperacionParcial': grpc.unary_unary_rpc_method_handler(
                    servicer.OperacionParcial,
                    request_deserializer=servicio__pb2.OperacionRequest.FromString,
                    response_serializer=servicio__pb2.ResultadoReceive.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Sistema', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Sistema', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sistema(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Listo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Sistema/Listo',
            servicio__pb2.Nulo.SerializeToString,
            servicio__pb2.Nulo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolicitudOperacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Sistema/SolicitudOperacion',
            servicio__pb2.OperacionRequest.SerializeToString,
            servicio__pb2.ResultadoReceive.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OperacionParcial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Sistema/OperacionParcial',
            servicio__pb2.OperacionRequest.SerializeToString,
            servicio__pb2.ResultadoReceive.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
